cafeteria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dishes.urls')),
    path('menu/',include('menu.urls')),
]

dishes/urls.py
from django.contrib import admin
from django.urls import path

from dishes.views import add_edit_dishes, delete_dishes, home, list_dishes


app_name = 'dishes'
urlpatterns = [
    path('', home, name="home"),
    path('dishes/', list_dishes, name="index"),
    path('dishe/add/', add_edit_dishes, name="add"),
    path('dishe/edit/<int:id>/', add_edit_dishes, name="edit"),
    path('dishe/delete/<int:id>/', delete_dishes, name="delete"),
]

menu/urls.py
from django.contrib import admin
from django.urls import path

from menu.views import add_edit_menu, delete_menu, list_menu


app_name = 'menu'
urlpatterns = [
    path('', list_menu, name="index"),
    path('/add/', add_edit_menu, name="add"),
    path('edit/<int:id>/', add_edit_menu, name="edit"),
    path('delete/<int:id>/', delete_menu, name="delete"),
]

dishes/models.py
from django.db import models

from base.models.helpers.named_date_time_model import NamedDateTimeModel



# Create your models here.



class DishesModel(NamedDateTimeModel):    
    summary = models.CharField(max_length=225)
    

    def __str__(self):
        return self.name

menu/models.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel


# Create your models here.

class MenuModel(DateTimeModel):
    dishes = models.OneToOneField('dishes.DishesModel', on_delete=models.CASCADE, related_name="menu_dishes")

    # def __str__(self):
    #     return self.name

dishes/forms.py
from django import forms

from dishes.models import DishesModel


class DishesForm(forms.ModelForm):
    class Meta:
        model = DishesModel
        fields = ('name','summary')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control'}),
        }

menu/forms.py
from django import forms

from menu.models import MenuModel


class MenuForm(forms.ModelForm):
    class Meta:
        model = MenuModel 
        fields = ('dishes',)
        

base/views.py
from django.shortcuts import render

# Create your views here.

dishes/views.py
from django.shortcuts import redirect, render

from dishes.forms import DishesForm
from dishes.models import DishesModel
from menu.models import MenuModel


# Create your views here.

def home(request):
    all_dishes = DishesModel.objects.all()
    all_menu = MenuModel.objects.all()
    total_menu = all_menu.count()
    total_dishes = all_dishes.count()
    return render(request, 'index.html', {"total_menu":total_menu,"total_dishes":total_dishes})


def list_dishes(request):
    search_field = request.GET.get('search')
    if search_field:
        founded_dishes = DishesModel.objects.filter(name__icontains=search_field)
        total = founded_dishes.count()

        return render(request, 'dishes/list.html', {'all_dishes': founded_dishes, 'total': total, 'search_field':search_field})
    else:
        all_dishes = DishesModel.objects.all()
        total = all_dishes.count()
        return render(request, 'dishes/list.html', {'all_dishes': all_dishes, 'total': total})


def add_edit_dishes(request,id=None):
    if id:
        dishes_selected = DishesModel.objects.get(id=id)
        dishes_form = DishesForm(instance=dishes_selected)
        if request.method == 'POST':
            form = DishesForm(request.POST, instance=dishes_selected)
            if form.is_valid():
                form.save()
                return redirect('dishes:index')
        return render(request, 'forms.html', {'dishes_form': dishes_form,'title':"Modification d'un plat"})
    else:
        dishes_form = DishesForm()
        if request.method == 'POST':
            form = DishesForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('dishes:index')
            else:
                print("Error")
        # return render(request, 'dishes/add_edit_dishes.html', {'dishes_form': dishes_form,'title':"Ajout d'un dishes"})
        return render(request, 'forms.html', {'dishes_form': dishes_form,'title':"Ajout d'un palt"})
    

def delete_dishes(request, id):
    dishes_to_delete = DishesModel.objects.get(id=id)
    dishes_to_delete.delete()
    return redirect('dishes:index')

menu/views.py
from django.shortcuts import redirect, render

from dishes.models import DishesModel
from menu.forms import MenuForm
from menu.models import MenuModel

# Create your views here.

def list_menu(request):
    search_field = request.GET.get('search')
    if search_field:
        founded_menu = MenuModel.objects.filter(id__icontains=search_field)
        total = founded_menu.count()

        return render(request, 'dishes/list.html', {'all_menu': founded_menu, 'total': total, 'search_field':search_field})
    else:
        all_menu = MenuModel.objects.all()
        all_dishes = DishesModel.objects.all()
        total = all_menu.count()
        return render(request, 'menu/list.html', {'all_menu': all_menu, 'all_dishes': all_dishes,'total': total})

def add_edit_menu(request,id=None):
    if id:
        menu_selected = MenuModel.objects.get(id=id)
        menu_form = MenuForm(instance=menu_selected)
        if request.method == 'POST':
            form = MenuForm(request.POST, instance=menu_selected)
            if form.is_valid():
                form.save()
                return redirect('menu:index')
        # return render(request, 'menu/add_edit_menu.html', {'menu_form': menu_form,'title':"Modification du menu"})
        return render(request, 'forms.html', {'menu_form': menu_form,'title':"Modification du menu"})

    else:
        menu_form = MenuForm()
        if request.method == 'POST':
            form = MenuForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('menu:index')
        # return render(request, 'menu/add_edit_menu.html', {'menu_form': menu_form,'title':"Ajout d'un menu"})
        return render(request, 'forms.html', {'menu_form': menu_form,'title':"Ajout du menu"})
        
    

def delete_menu(request, id):
    menu_to_delete = MenuModel.objects.get(id=id)
    menu_to_delete.delete()
    return redirect('menu:index')

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png" %}" /> 
    <link rel="icon" type="image/png"href="{% static "assets/img/favicon.png" %}" />

    <!--     Fonts and icons     -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
    />

    <!-- Nucleo Icons -->
    <link href="{% static "assets/css/nucleo-icons.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/nucleo-svg.css" %}" rel="stylesheet"/>

    <!-- Font Awesome Icons -->
    <script
      src="https://kit.fontawesome.com/42d5adcbca.js"
      crossorigin="anonymous"
    ></script>

    <!-- Material Icons -->
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
      rel="stylesheet"
    />

    <!-- CSS Files -->

    <link id="pagestyle" href="{% static "./assets/css/material-dashboard.css" %}" rel="stylesheet" />

    <!-- Nepcha Analytics (nepcha.com) -->
    <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
    <script
      defer
      data-site="YOUR_DOMAIN_HERE"
      src="https://api.nepcha.com/js/nepcha-analytics.js"
    ></script>

    <title>{% block title %}Ma cantine scolaire{% endblock title %}</title>
  </head>
  <body class="g-sidenav-show bg-gray-100">
    <aside
      class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
      id="sidenav-main"
    >
      <div class="sidenav-header">
        <i
          class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
          aria-hidden="true"
          id="iconSidenav"
        ></i>
        <a class="navbar-brand m-0" href="/" >
          <img
            src="{% static "./assets/img/logo-ct.png" %}"
            class="navbar-brand-img h-100"
            alt="main_logo"
          />
          <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
        </a>
      </div>

      <hr class="horizontal light mt-0 mb-2" />

      <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url "menu:index" %}">
              <div
                class="text-white text-center me-2 d-flex align-items-center justify-content-center"
              >
                <span class="material-symbols-outlined text-white">menu_book</span>
              </div>

              <span class="nav-link-text ms-1">Menus</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url "dishes:index" %}">
              <div
                class="text-white text-center me-2 d-flex align-items-center justify-content-center"
              >
                <span class="material-symbols-outlined">local_cafe</span>
              </div>

              <span class="nav-link-text ms-1">Plats</span>
            </a>
          </li>
        </ul>
      </div>
    </aside>

    <main class="main-content border-radius-lg">
      {% block content %}
      <!-- Your page content here -->
      {% endblock content %}
      <div class="container-fluid py-4">
      
        <footer class="footer py-4">
          <div class="container-fluid">
            <div class="row align-items-center justify-content-lg-between">
              <div class="col-lg-6 mb-lg-0 mb-4">
                <div
                  class="copyright text-center text-sm text-muted text-lg-start"
                >
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  ADA
                </div>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </main>

    <!--   Core JS Files   -->
    <script src="{% static "./assets/js/core/popper.min.js" %}"></script>
    <script src="{% static "./assets/js/core/bootstrap.min.js" %}"></script>
    <script src="{% static "./assets/js/plugins/perfect-scrollbar.min.js" %}"></script>
    <script src="{% static "./assets/js/plugins/smooth-scrollbar.min.js" %}"></script>
    <script>
      var win = navigator.platform.indexOf("Win") > -1;
      if (win && document.querySelector("#sidenav-scrollbar")) {
        var options = {
          damping: "0.5",
        };
        Scrollbar.init(document.querySelector("#sidenav-scrollbar"), options);
      }
    </script>

    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{% static "assets/js/material-dashboard.min.js" %}"></script>
  </body>
</html>

templates/dishes/list.html
{% extends "base.html" %}
{% block title %}Liste des plats{% endblock title %} {% block content %}
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">


      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <ul class="navbar-nav  justify-content-start">
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url "dishes:add" %}">Ajouter un plat</a>
          </li>
        </ul>
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        <form method="GET" style="display:flex; ">
       
          <div class="input-group input-group-outline">
            <label class="form-label">Recherche par nom</label>
            <input type="text" class="form-control" name="search" value="{{ search_field }}">
          </div>
       
        <ul class="navbar-nav  justify-content-end">
          <li class="nav-item d-flex align-items-center">
            <button class="btn btn-outline-primary btn-sm mb-0 me-3" type="submit">Recherche</button>
          </li>
        </ul>
      </form>
    </div>
      </div>
    </div>
  </nav>

  <div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Liste des plats ({{ total }})</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Libelle</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                </tr>
              </thead>
              <tbody>
                {% for dishe in all_dishes  %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{dishe.name}}</h6>
                      </div>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <a href="{% url "dishes:edit" dishe.id %}" class="badge badge-sm bg-gradient-success">Modifier</a>
                    <a href="{% url "dishes:delete" dishe.id %}" class="badge badge-sm bg-gradient-danger">Supprimer</a>
                  </td>
                </tr>
                {% endfor %}
                
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/forms.html
{% extends "base.html" %} {% load crispy_forms_tags %} 
{% block title%}{{title}}{% endblock title %} {%block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div
          class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12"
        >
          <div class="card card-plain">
            <div class="card-header">
              <h4 class="font-weight-bolder">Formulaire {{title}}</h4>
            </div>
            <div class="card-body">
              <form role="form" method="POST">
                {% csrf_token %}
                {{ dishes_form | crispy }} {{ menu_form | crispy }}
                <div class="text-center">
                  <button
                    type="submit"
                    class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0"
                  >
                    Enregistrer
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/index.html
{% extends "base.html" %} {% block title %}HomePage{% endblock title %} 
{% block content %}
<main class="main-content border-radius-lg">
  <div class="container-fluid py-4">
    <div style="margin-left: 30%">
      <h1>Bienvenue dans " Ma Cantine! "</h1>
      <p>
        Découvrez notre menu complet avec des plats de gastronomie française et
        une cuisine vegan et sans gluten.
      </p>
      
      <div style="display:flex; justify-content:space-around; margin-bottom:10vh">
        <div style="padding:20px;box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;  text-color:white; width:fit-content; border-radius:15px"> 
            <p> Nombre de menu</p>
            <p>{{total_menu}}</p>
        </div>
        <div style="padding:20px; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px; text-color:white; width:fit-content; border-radius:15px"> 
            <p> Nombre de plats</p>
            <p>{{total_dishes}}</p>
        </div>
      </div>
      <div style="display:flex; justify-content:space-around; margin-bottom:10vh">
      <a href="{% url "menu:index" %}" class="btn btn-primary">Voir les menu</a>
      <a href="{% url "dishes:index" %}" class="btn btn-primary">Voir les plats </a>
    </div>
    </div>
  </div>
</main>
{% endblock content %}

templates/menu/list.html
{% extends "base.html" %}
{% block title %}Liste des menus{% endblock title %} {% block content %}
<div class="row">
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
        <div class="container-fluid py-1 px-3">
    
    
          <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <ul class="navbar-nav  justify-content-start">
              <li class="nav-item d-flex align-items-center">
                <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url "menu:add" %}">Ajouter un menu</a>
              </li>
            </ul>
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
              <form method="GET" style="display:flex; ">
             
                <div class="input-group input-group-outline">
                  <label class="form-label">Recherche par id</label>
                  <input type="number" class="form-control" name="search" value="{{ search_field }}">
                </div>
             
              <ul class="navbar-nav  justify-content-end">
                <li class="nav-item d-flex align-items-center">
                  <button class="btn btn-outline-primary btn-sm mb-0 me-3" type="submit">Recherche</button>
                </li>
              </ul>
            </form>
          </div>
          </div>
        </div>
      </nav>
  <div class="col-12">
    <div class="card my-4">
      <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
        <div
          class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3"
        >
          <h6 class="text-white text-capitalize ps-3">Liste des menus ({{ total }})</h6>
        </div>
      </div>
      <div class="card-body px-0 pb-2">
        <div class="table-responsive p-0">
          <table class="table align-items-center mb-0">
            <thead>
              <tr>
                <th
                  class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                >
                  Date
                </th>
                <th
                  class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                >
                  Plat
                </th>
                <th
                  class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"
                ></th>
              </tr>
            </thead>
            <tbody>
              {% for menu in all_menu %}
              <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-sm">{{ menu.creation_date }}</h6>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-sm">{{menu.dishes.name}}</h6>
                    </div>
                  </div>
                </td>
                <td class="align-middle text-center text-sm">
                  <a
                    href="{% url 'menu:edit' menu.id %}"
                    class="badge badge-sm bg-gradient-success"
                  >
                    Modifier
                  </a>
                  <a
                    href="{% url 'menu:delete' menu.id %}"
                    class="badge badge-sm bg-gradient-danger"
                  >
                    Supprimer
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}